version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification
    command: python -m app.main
    ports:
      - "8001:8000"
    volumes:
      - ./data:/notification/data
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=notification
      - DB_USER=postgres
      - DB_PASS=52949235
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=52949235
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
